# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          to: pandalearnstocode@gmail.com,shekhar.devanshee@gmail.com
          from: Aritra Biswas # <user@example.com>
          secure: true
          html_body: file://email-templates-master/10/index.html
          attachments: app.log
          convert_markdown: true
          content_type: html
          ignore_cert: true
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: high
